package com.zyiot.pm.entity.comm;

// default package
// Generated 2013-12-2 11:01:13 by Hibernate Tools 3.4.0.CR1

/**
 * ZyProvince generated by hbm2java
 */
public class ZyProvince implements java.io.Serializable
{
	
	private Integer	provinceid;
	private String	provincecode;
	private String	provincename;
	
	public ZyProvince()
	{
	}
	
	public ZyProvince(String provincecode, String provincename)
	{
		this.provincecode = provincecode;
		this.provincename = provincename;
	}
	
	public Integer getProvinceid()
	{
		return this.provinceid;
	}
	
	public void setProvinceid(Integer provinceid)
	{
		this.provinceid = provinceid;
	}
	
	public String getProvincecode()
	{
		return this.provincecode;
	}
	
	public void setProvincecode(String provincecode)
	{
		this.provincecode = provincecode;
	}
	
	public String getProvincename()
	{
		return this.provincename;
	}
	
	public void setProvincename(String provincename)
	{
		this.provincename = provincename;
	}
	
}
