package com.zyiot.pm.entity.ht;

// default package
// Generated 2013-12-2 11:01:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ZyBussinessinfo generated by hbm2java
 */
public class ZyBussinessinfo implements java.io.Serializable
{
	
	private String	pkId;
	private String	bussId;
	private String	bussCode;
	private String	bussOrgCode;
	private Date	bussStartDate;
	private Date	bussEndDate;
	private String	bussName;
	private String	bussSimp;
	private int		provincecode;
	private int		citycode;
	private int		areacode;
	private String	townName;
	private int		bussUcount;
	private String	bussOperRevenue;
	private String	bussRate;
	private String	expCode;
	private String	servCode;
	private String	classCode1;
	private String	bussQq;
	private String	bussManagerName;
	private String	bussManagerPhone;
	private String	bussConnName;
	private String	bussConnPhone;
	private String	bussFax;
	private String	bussConnMobile;
	private String	bussFinanceName;
	private String	bussFinancePhone;
	private String	bussAddr;
	private String	isSign;
	private String	isThird;
	private String	makeUser;
	private String	memo;
	private String	createDateUser;
	private Date	createDate;
	private String	lastDateUser;
	private Date	lastDate;
	
	public ZyBussinessinfo()
	{
	}
	
	public ZyBussinessinfo(String pkId, String bussId, String bussCode, Date bussStartDate, Date bussEndDate, String bussName, int provincecode, int citycode, int areacode, int bussUcount, String bussRate, String bussManagerName, String bussManagerPhone, String bussConnName, String bussConnPhone, String bussConnMobile, String bussFinanceName, String bussFinancePhone, String bussAddr, String isSign, String isThird)
	{
		this.pkId = pkId;
		this.bussId = bussId;
		this.bussCode = bussCode;
		this.bussStartDate = bussStartDate;
		this.bussEndDate = bussEndDate;
		this.bussName = bussName;
		this.provincecode = provincecode;
		this.citycode = citycode;
		this.areacode = areacode;
		this.bussUcount = bussUcount;
		this.bussRate = bussRate;
		this.bussManagerName = bussManagerName;
		this.bussManagerPhone = bussManagerPhone;
		this.bussConnName = bussConnName;
		this.bussConnPhone = bussConnPhone;
		this.bussConnMobile = bussConnMobile;
		this.bussFinanceName = bussFinanceName;
		this.bussFinancePhone = bussFinancePhone;
		this.bussAddr = bussAddr;
		this.isSign = isSign;
		this.isThird = isThird;
	}
	
	public ZyBussinessinfo(String pkId, String bussId, String bussCode, String bussOrgCode, Date bussStartDate, Date bussEndDate, String bussName, String bussSimp, int provincecode, int citycode, int areacode, String townName, int bussUcount, String bussOperRevenue, String bussRate, String expCode, String servCode, String classCode1, String bussQq, String bussManagerName, String bussManagerPhone, String bussConnName, String bussConnPhone, String bussFax, String bussConnMobile, String bussFinanceName, String bussFinancePhone, String bussAddr, String isSign, String isThird, String makeUser, String memo, String createDateUser, Date createDate, String lastDateUser, Date lastDate)
	{
		this.pkId = pkId;
		this.bussId = bussId;
		this.bussCode = bussCode;
		this.bussOrgCode = bussOrgCode;
		this.bussStartDate = bussStartDate;
		this.bussEndDate = bussEndDate;
		this.bussName = bussName;
		this.bussSimp = bussSimp;
		this.provincecode = provincecode;
		this.citycode = citycode;
		this.areacode = areacode;
		this.townName = townName;
		this.bussUcount = bussUcount;
		this.bussOperRevenue = bussOperRevenue;
		this.bussRate = bussRate;
		this.expCode = expCode;
		this.servCode = servCode;
		this.classCode1 = classCode1;
		this.bussQq = bussQq;
		this.bussManagerName = bussManagerName;
		this.bussManagerPhone = bussManagerPhone;
		this.bussConnName = bussConnName;
		this.bussConnPhone = bussConnPhone;
		this.bussFax = bussFax;
		this.bussConnMobile = bussConnMobile;
		this.bussFinanceName = bussFinanceName;
		this.bussFinancePhone = bussFinancePhone;
		this.bussAddr = bussAddr;
		this.isSign = isSign;
		this.isThird = isThird;
		this.makeUser = makeUser;
		this.memo = memo;
		this.createDateUser = createDateUser;
		this.createDate = createDate;
		this.lastDateUser = lastDateUser;
		this.lastDate = lastDate;
	}
	
	public String getPkId()
	{
		return this.pkId;
	}
	
	public void setPkId(String pkId)
	{
		this.pkId = pkId;
	}
	
	public String getBussId()
	{
		return this.bussId;
	}
	
	public void setBussId(String bussId)
	{
		this.bussId = bussId;
	}
	
	public String getBussCode()
	{
		return this.bussCode;
	}
	
	public void setBussCode(String bussCode)
	{
		this.bussCode = bussCode;
	}
	
	public String getBussOrgCode()
	{
		return this.bussOrgCode;
	}
	
	public void setBussOrgCode(String bussOrgCode)
	{
		this.bussOrgCode = bussOrgCode;
	}
	
	public Date getBussStartDate()
	{
		return this.bussStartDate;
	}
	
	public void setBussStartDate(Date bussStartDate)
	{
		this.bussStartDate = bussStartDate;
	}
	
	public Date getBussEndDate()
	{
		return this.bussEndDate;
	}
	
	public void setBussEndDate(Date bussEndDate)
	{
		this.bussEndDate = bussEndDate;
	}
	
	public String getBussName()
	{
		return this.bussName;
	}
	
	public void setBussName(String bussName)
	{
		this.bussName = bussName;
	}
	
	public String getBussSimp()
	{
		return this.bussSimp;
	}
	
	public void setBussSimp(String bussSimp)
	{
		this.bussSimp = bussSimp;
	}
	
	public int getProvincecode()
	{
		return this.provincecode;
	}
	
	public void setProvincecode(int provincecode)
	{
		this.provincecode = provincecode;
	}
	
	public int getCitycode()
	{
		return this.citycode;
	}
	
	public void setCitycode(int citycode)
	{
		this.citycode = citycode;
	}
	
	public int getAreacode()
	{
		return this.areacode;
	}
	
	public void setAreacode(int areacode)
	{
		this.areacode = areacode;
	}
	
	public String getTownName()
	{
		return this.townName;
	}
	
	public void setTownName(String townName)
	{
		this.townName = townName;
	}
	
	public int getBussUcount()
	{
		return this.bussUcount;
	}
	
	public void setBussUcount(int bussUcount)
	{
		this.bussUcount = bussUcount;
	}
	
	public String getBussOperRevenue()
	{
		return this.bussOperRevenue;
	}
	
	public void setBussOperRevenue(String bussOperRevenue)
	{
		this.bussOperRevenue = bussOperRevenue;
	}
	
	public String getBussRate()
	{
		return this.bussRate;
	}
	
	public void setBussRate(String bussRate)
	{
		this.bussRate = bussRate;
	}
	
	public String getExpCode()
	{
		return this.expCode;
	}
	
	public void setExpCode(String expCode)
	{
		this.expCode = expCode;
	}
	
	public String getServCode()
	{
		return this.servCode;
	}
	
	public void setServCode(String servCode)
	{
		this.servCode = servCode;
	}
	
	public String getClassCode1()
	{
		return this.classCode1;
	}
	
	public void setClassCode1(String classCode1)
	{
		this.classCode1 = classCode1;
	}
	
	public String getBussQq()
	{
		return this.bussQq;
	}
	
	public void setBussQq(String bussQq)
	{
		this.bussQq = bussQq;
	}
	
	public String getBussManagerName()
	{
		return this.bussManagerName;
	}
	
	public void setBussManagerName(String bussManagerName)
	{
		this.bussManagerName = bussManagerName;
	}
	
	public String getBussManagerPhone()
	{
		return this.bussManagerPhone;
	}
	
	public void setBussManagerPhone(String bussManagerPhone)
	{
		this.bussManagerPhone = bussManagerPhone;
	}
	
	public String getBussConnName()
	{
		return this.bussConnName;
	}
	
	public void setBussConnName(String bussConnName)
	{
		this.bussConnName = bussConnName;
	}
	
	public String getBussConnPhone()
	{
		return this.bussConnPhone;
	}
	
	public void setBussConnPhone(String bussConnPhone)
	{
		this.bussConnPhone = bussConnPhone;
	}
	
	public String getBussFax()
	{
		return this.bussFax;
	}
	
	public void setBussFax(String bussFax)
	{
		this.bussFax = bussFax;
	}
	
	public String getBussConnMobile()
	{
		return this.bussConnMobile;
	}
	
	public void setBussConnMobile(String bussConnMobile)
	{
		this.bussConnMobile = bussConnMobile;
	}
	
	public String getBussFinanceName()
	{
		return this.bussFinanceName;
	}
	
	public void setBussFinanceName(String bussFinanceName)
	{
		this.bussFinanceName = bussFinanceName;
	}
	
	public String getBussFinancePhone()
	{
		return this.bussFinancePhone;
	}
	
	public void setBussFinancePhone(String bussFinancePhone)
	{
		this.bussFinancePhone = bussFinancePhone;
	}
	
	public String getBussAddr()
	{
		return this.bussAddr;
	}
	
	public void setBussAddr(String bussAddr)
	{
		this.bussAddr = bussAddr;
	}
	
	public String getIsSign()
	{
		return this.isSign;
	}
	
	public void setIsSign(String isSign)
	{
		this.isSign = isSign;
	}
	
	public String getIsThird()
	{
		return this.isThird;
	}
	
	public void setIsThird(String isThird)
	{
		this.isThird = isThird;
	}
	
	public String getMakeUser()
	{
		return this.makeUser;
	}
	
	public void setMakeUser(String makeUser)
	{
		this.makeUser = makeUser;
	}
	
	public String getMemo()
	{
		return this.memo;
	}
	
	public void setMemo(String memo)
	{
		this.memo = memo;
	}
	
	public String getCreateDateUser()
	{
		return this.createDateUser;
	}
	
	public void setCreateDateUser(String createDateUser)
	{
		this.createDateUser = createDateUser;
	}
	
	public Date getCreateDate()
	{
		return this.createDate;
	}
	
	public void setCreateDate(Date createDate)
	{
		this.createDate = createDate;
	}
	
	public String getLastDateUser()
	{
		return this.lastDateUser;
	}
	
	public void setLastDateUser(String lastDateUser)
	{
		this.lastDateUser = lastDateUser;
	}
	
	public Date getLastDate()
	{
		return this.lastDate;
	}
	
	public void setLastDate(Date lastDate)
	{
		this.lastDate = lastDate;
	}
	
}
